export const siteSettingsFields = [
  { name: "logoUrl", label: "Site Logo", type: "image" },
  { name: "heroBackgroundUrl", label: "Default Hero Background", type: "image", hint: "Fallback used by any page that hasn't set its own hero image." },
  { name: "phonePrimary", label: "Phone — Primary", type: "text" },
  { name: "phoneSecondary", label: "Phone — Secondary", type: "text" },
  { name: "phoneTertiary", label: "Phone — Tertiary", type: "text" },
  { name: "emailPrimary", label: "Email — Primary", type: "text" },
  { name: "emailBooking", label: "Email — Booking / Info", type: "text" },
  { name: "facebookUrl", label: "Facebook URL", type: "text" },
  { name: "instagramUrl", label: "Instagram URL", type: "text" },
  { name: "youtubeUrl", label: "YouTube URL", type: "text" },
  { name: "contactPersonName", label: "Contact Person — Name", type: "text", hint: 'Shown on the Contact page, e.g. "MR. ANKIT"' },
  { name: "contactPersonTitle", label: "Contact Person — Title", type: "text", hint: 'e.g. "(Official Management)"' },
  { name: "footerHeading", label: "Footer — Heading", type: "text" },
  { name: "footerHighlightWord", label: "Footer — Highlighted Word", type: "text", hint: "Must be a word that appears in the heading above — shown in gold." },
  { name: "footerBackgroundUrl", label: "Footer — Background Image", type: "image" },
  { name: "footerSubtext", label: "Footer — Subtext", type: "textarea" },
  { name: "footerCopyrightText", label: "Footer — Copyright Line", type: "text" },
];
